name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Yarn build
        run: yarn build
      - name: Yarn lint
        run: yarn lint
      - name: Yarn test
        run: yarn test
